### ISSUE TITLE
Add classes for a basic flexbox layout

### ISSUE THREAD

**Issue by barcia** [opositatest/design-tokens#5]
```scss
.l-flex {
    display: flex;
}

.l-marginLeft-auto {
    margin-left: auto;
}
```
